```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Applied Python Exercise 1

## Goal -- Print every line in a file

Write Python code that works towards recreating the Bash tool `head`, displaying every line in a file: `random_snippet.vcf`

## Learning Objectives

After going through this module, students should be able to: 

* State the sub-steps needed to meet the coding goal
* Use the following datatypes, structures, and fundamentals to meet the coding goal:
  * variable assignment
  * strings
  * opening a file
  * for loop
  * printing output

## Coding Blueprint

Within this module, you will write code that displays every line in an input file. To complete this goal, consider the most basic tasks that would be required.

First, we need to SET the input file
Second, FOR every line in the open file
  PRINT the line
END FOR

### SET the input file

Let's focus on that first step: SET the input file. One important thing when breaking down tasks into smaller, manageable steps is asking yourself what information is available in your script, and what information you need to define or store in variables. The filename is something that will need to be assigned to a variable so that it is available information. 

### FOR every line in the open file ...

Let's focus on the FOR portion of the pseudocode now, specifically building the `for` loop structure by considering each of the 3 components discussed earlier:

1. The `for` statement

  Which `for` statement pattern best fits the task you want to accomplish of printing every line in the file? We'll see as we build the code that the first pattern, `for line in file`, will work very well for this task because all we need is to work with the items (lines) contained in a collection (the file) item-by-item.
  
  However, we will have to slightly edit this pattern to make sure we're working with the contents of the file, and not the contents of the string variable storing the filename. If we don't open the file and the `file` variable refers to the string of the filename, then `line` will just be the letters of the filename one at a time. Therefore, we'll want to make sure that `file` refers to the open file.

### PRINT the line

2. The body of the `for` loop

  We've already defined this well - we want to PRINT the line.

3. Any variable initialization before the `for` statement

  Is there any need to initialize a variable before the `for` loop that you will edit within the body of the loop? In this case, because we're printing every line in the file, there's no need to initilalize a variable beforehand.

## Building the code

**Create a new Python script**

### SET the input file

To SET what the input file is, we will create a variable which stores the string of the filename for the input file.

Consult the notes on variable assignment earlier to SET a variable equal to the input file. Within your Python script, write a line of code that does this. 

ANSWER:
```{python, eval = FALSE}
filename = "random_snippet.vcf"
```

### FOR every line in the open file

Then, that variable is just storing the name of the file. The actual file contents, or the lines of the file, aren't available to Python until the file is opened. Consult the notes on the built-in Python function `open()` and use the determined structure of the `for` statement from the pseudocode section above to open the file and begin the `for` loop architecture. Within your Python script, write a line of code that does this.

ANSWER:
```{python, eval = FALSE}
for line in open(filename):
```

### PRINT the line

Now that we have the first component of the `for` loop, we can write the body of the `for` loop so that each line is printed as output. Consult the notes on the `print()` function indenting the body of the `for` loop under the `for` statement. Within your Python script, write a line of code that does this.

ANSWER:
```{python, eval = FALSE}
  print(line)
```

If we were just to use the code above, there would be a blank line printed at the end of each line from the file. We can remove the blank lines from the output by using a `parameter` in the `print()` function, specifically `end=`. By default, the end of a printed line from the `print()` function in python is what's called a newline character (`\n`). This will appear as a blank line if what is being printed already has a newline character at the end of it, which our input file does. Therefore, we can set `end` equal to an empty string, which is just two quotes next to each other without any space, and this will remove or suppress those blank lines in the output. Edit the line of code within your Python script to do this.

```{python, eval = FALSE}
  print(line, end="")
```

Finally, within our Python script, we have the three lines of code together which makes our complete intended goal code -- code that prints every line in a file.

**Use the command line to run the Python script and look at the output.**

## Complete Intended Goal Code

```{python, eval = FALSE}
filename = "random_snippet.vcf" #SET the input filename
for line in open(filename): #FOR every line in the open file
  print(line, end="") #PRINT the line
```